### PR TITLE
updated config to move to Yii 3.x core

### PR DESCRIPTION
**Pull request by schmunk42**

### CODE REVIEW

**Comment by samdark** [comment]
That's not needed. We have native github feature for moving issues.

**Comment by schmunk42** [comment]
Can issues like this https://github.com/yiisoft/yii2/issues/14862 (tagged 3.0) be moved to yii-core?

How will we proceed with issues, branches and development regarding 2.0, 2.1, 3.x? E.g. should the 3.x branch be removed from yii2-framework?

**Comment by cebe** [comment]
yes, 3.0 branch does not make sense for yii2 repos, but we might keep it until we have alpha release of yii3 which sets the exact repos we have.

**Comment by samdark** [comment]
@hiqsol made a dangerous thing running production on 3.x branch from main repo. That's why it's still there :)

**Comment by hiqsol** [comment]
Actually, it was @SilverFire :)
We'll fix it soon, but please keep 3.0 branch meanwhile :)

**Comment by cebe** [comment]
As I said, when we have defined how Yii 3 will look like exactly (alpha release) we can remove old branches.

**Comment by schmunk42** [comment]
There's an alpha btw ;) https://github.com/yiisoft/yii2/releases/tag/3.0.0-alpha1

**Comment by cebe** [comment]
oh, well... alpha2 then :-D

**Pull request closed without merging**
